name: Release & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_major_version: ${{ steps.semantic.outputs.new_release_major_version }}
      new_release_minor_version: ${{ steps.semantic.outputs.new_release_minor_version }}
      new_release_patch_version: ${{ steps.semantic.outputs.new_release_patch_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          # Use custom config that forces minor version increment
          npx semantic-release --extends ./.github/semantic-release-config.js

  docker-build-amd64:
    name: Build Docker Image (amd64)
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=Claude Flow Dagger
            org.opencontainers.image.description=Dagger module for Claude Flow CLI with non-interactive mode support
            org.opencontainers.image.vendor=Badal.io
            org.opencontainers.image.version=${{ needs.semantic-release.outputs.new_release_version }}

      - name: Build and push Docker image (amd64)
        id: build-amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-amd64
          cache-to: type=gha,mode=max,scope=buildkit-amd64
          build-args: |
            VERSION=${{ needs.semantic-release.outputs.new_release_version }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
          provenance: false
          sbom: false
          outputs: type=image,name=ghcr.io/${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
      
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build-amd64.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-amd64
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker-build-arm64:
    name: Build Docker Image (arm64)
    runs-on: ubuntu-24.04-arm  # Will use QEMU for arm64, or can use self-hosted ARM runner
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

# Only use if arm runners aren't available
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#        if: env.RUNNER_ARCH != 'ARM64'
#        with:
#          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=Claude Flow Dagger
            org.opencontainers.image.description=Dagger module for Claude Flow CLI with non-interactive mode support
            org.opencontainers.image.vendor=Badal.io
            org.opencontainers.image.version=${{ needs.semantic-release.outputs.new_release_version }}

      - name: Build and push Docker image (arm64)
        id: build-arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=buildkit-arm64
          cache-to: type=gha,mode=max,scope=buildkit-arm64
          build-args: |
            VERSION=${{ needs.semantic-release.outputs.new_release_version }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}
          provenance: false
          sbom: false
          outputs: type=image,name=ghcr.io/${{ github.repository }},push-by-digest=true,name-canonical=true,push=true
      
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build-arm64.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-arm64
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  docker-manifest:
    name: Create Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs: [semantic-release, docker-build-amd64, docker-build-arm64]
    if: needs.semantic-release.outputs.new_release_published == 'true'
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.semantic-release.outputs.new_release_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.semantic-release.outputs.new_release_version }}
            type=semver,pattern={{major}},value=${{ needs.semantic-release.outputs.new_release_version }}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Claude Flow Dagger
            org.opencontainers.image.description=Dagger module for Claude Flow CLI with non-interactive mode support
            org.opencontainers.image.vendor=Badal.io
            org.opencontainers.image.version=${{ needs.semantic-release.outputs.new_release_version }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/${{ github.repository }}@sha256:%s ' *)

      - name: Create Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << EOF > release-notes.md
          ## 🐳 Docker Image

          \`\`\`bash
          docker pull ghcr.io/${{ github.repository }}:${{ needs.semantic-release.outputs.new_release_version }}
          \`\`\`

          ### Available Tags:
          - \`latest\` - Latest stable release
          - \`${{ needs.semantic-release.outputs.new_release_version }}\` - This release
          - \`${{ needs.semantic-release.outputs.new_release_major_version }}\` - Major version
          - \`${{ needs.semantic-release.outputs.new_release_major_version }}.${{ needs.semantic-release.outputs.new_release_minor_version }}\` - Major.Minor version

          ### Multi-Architecture Support:
          - \`linux/amd64\` - Native x86_64 build
          - \`linux/arm64\` - Native ARM64 build
          
          ### Build Improvements:
          - Architecture-specific native builds for better performance
          - Provenance attestations included for security
          - Optimized caching per architecture
          EOF

          gh release edit v${{ needs.semantic-release.outputs.new_release_version }} \
            --notes-file release-notes.md \
            --repo ${{ github.repository }} || true
